ui:
  time_format: 24hour

mqtt:
  enabled: false

detectors:
  ov:
    type: openvino
    device: GPU

model:
  model_type: yolo-generic
  width: 320
  height: 320
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolov9-s-320.onnx
  labelmap_path: /labelmap/coco-80.txt

audio:
  enabled: true
  listen:
    - yell
    - music
    - scream
    - speech

ffmpeg:
  hwaccel_args: preset-intel-qsv-h264

detect:
  enabled: true
  fps: 10

notifications:
  enabled: false
  email: frigate@ccrsxx.com

record:
  enabled: true
  continuous:
    days: 30
  motion:
    days: 30
  alerts:
    retain:
      days: 30
      mode: all
  detections:
    retain:
      days: 30
      mode: all

semantic_search:
  enabled: true
  reindex: false
  model_size: large

genai:
  provider: gemini
  api_key: '{FRIGATE_GEMINI_API_KEY}'
  model: gemini-2.5-flash

go2rtc:
  webrtc:
    candidates:
      - 192.168.1.100:8555
      - stun:8555
  streams:
    street_cam:
      - '{FRIGATE_RTSP_CAM_STREET}'
    garage_cam:
      - '{FRIGATE_RTSP_CAM_GARAGE}'
    bedroom_cam:
      - '{FRIGATE_RTSP_CAM_BEDROOM}'
      - '{FRIGATE_ISAPI_CAM_BEDROOM}'
      - ffmpeg:bedroom_cam#audio=opus
    bedroom_cam_sub:
      - '{FRIGATE_RTSP_CAM_BEDROOM_SUB}'
      - ffmpeg:bedroom_cam_sub#audio=opus
    kitchen_cam:
      - '{FRIGATE_RTSP_CAM_KITCHEN}'
      - '{FRIGATE_ISAPI_CAM_KITCHEN}'
      - ffmpeg:kitchen_cam#audio=opus
    kitchen_cam_sub:
      - '{FRIGATE_RTSP_CAM_KITCHEN_SUB}'
      - ffmpeg:kitchen_cam_sub#audio=opus
    terrace_cam:
      - '{FRIGATE_RTSP_CAM_TERRACE}'
      - '{FRIGATE_ISAPI_CAM_TERRACE}'
      - ffmpeg:terrace_cam#audio=opus
    terrace_cam_sub:
      - '{FRIGATE_RTSP_CAM_TERRACE_SUB}'
      - ffmpeg:terrace_cam_sub#audio=opus

cameras:
  street_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/street_cam
          roles:
            - record
            - detect
    audio:
      enabled: false
    notifications:
      enabled: true
    zones:
      before_street:
        coordinates: 0.344,0.614,0.357,1,0.85,1,0.782,0.565
        loitering_time: 0
        friendly_name: Before street
        inertia: 3
    review:
      alerts:
        required_zones: before_street
      detections:
        required_zones: before_street
  garage_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/garage_cam
    audio:
      enabled: false
    detect:
      enabled: false
    record:
      enabled: false
    notifications:
      enabled: false
  bedroom_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/bedroom_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/bedroom_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    notifications:
      enabled: true
    objects:
      genai:
        enabled: false
    zones:
      bed:
        coordinates: 0.295,0.645,0.279,1,0.842,1,0.78,0.7
        loitering_time: 0
        friendly_name: Bed
      doorway:
        coordinates: 0.299,0.638,0.419,0.652,0.458,0,0.342,0
        loitering_time: 0
        friendly_name: Doorway
        inertia: 3
    review:
      alerts:
        required_zones:
          - doorway
          - bed
      detections:
        required_zones:
          - bed
          - doorway
  kitchen_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/kitchen_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/kitchen_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    notifications:
      enabled: true
    objects:
      genai:
        enabled: false
  terrace_cam:
    enabled: true
    ffmpeg:
      inputs:
        - path: rtsp://127.0.0.1:8554/terrace_cam
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/terrace_cam_sub
          input_args: preset-rtsp-restream
          roles:
            - audio
            - detect
    notifications:
      enabled: true
    objects:
      genai:
        enabled: false

objects:
  track:
    - car
    - cat
    - bird
    - mouse
    - person
    - bicycle
    - motorcycle
  genai:
    enabled: true

auth:
  roles:
    family:
      - terrace_cam
      - garage_cam
      - street_cam

camera_groups:
  Outdoor:
    order: 1
    icon: LuLogOut
    cameras:
      - kitchen_cam
      - terrace_cam
      - garage_cam
      - street_cam

version: 0.17-0
