# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json

radarr:
  radarr:
    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    quality_definition:
      type: movie

    quality_profiles:
      # HD Bluray + WEB
      - trash_id: d1d67249d3890e49bc12e275d989a7e9
        name: HD Bluray + WEB
        reset_unmatched_scores:
          enabled: true

      # UHD Bluray + WEB
      - trash_id: 64fb5f9858489bdac2af690e27c8f42f
        name: UHD Bluray + WEB
        reset_unmatched_scores:
          enabled: true

      # Remux + WEB 1080p
      - trash_id: 9ca12ea80aa55ef916e3751f4b874151
        name: Remux + WEB 1080p
        reset_unmatched_scores:
          enabled: true

      # Remux + WEB 2160p
      - trash_id: fd161a61e3ab826d3a22d53f935696dd
        name: Remux + WEB 2160p
        reset_unmatched_scores:
          enabled: true
