# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

radarr:
  radarr:
    base_url: !env_var RADARR_BASE_URL
    api_key: !env_var RADARR_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    include:
      # Quality Definition
      - template: radarr-quality-definition-movie

      # HD Bluray + WEB
      - template: radarr-quality-profile-hd-bluray-web
      - template: radarr-custom-formats-hd-bluray-web

      # UHD Bluray + WEB
      - template: radarr-quality-profile-uhd-bluray-web
      - template: radarr-custom-formats-uhd-bluray-web

      # Remux + WEB 1080p
      - template: radarr-quality-profile-remux-web-1080p
      - template: radarr-custom-formats-remux-web-1080p

      # Remux + WEB 2160p
      - template: radarr-quality-profile-remux-web-2160p
      - template: radarr-custom-formats-remux-web-2160p

    # Disable upgrades on all profiles
    quality_profiles:
      - name: HD Bluray + WEB
        upgrade:
          allowed: false

      - name: UHD Bluray + WEB
        upgrade:
          allowed: false

      - name: Remux + WEB 1080p
        upgrade:
          allowed: false

      - name: Remux + WEB 2160p
        upgrade:
          allowed: false
