# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

radarr:
  radarr-anime:
    base_url: !env_var RADARR_ANIME_BASE_URL
    api_key: !env_var RADARR_ANIME_API_KEY

    media_naming:
      folder: default
      movie:
        rename: true
        standard: standard

    include:
      - template: radarr-quality-definition-anime
      - template: radarr-quality-profile-anime
      - template: radarr-custom-formats-anime
