# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json

sonarr:
  sonarr:
    base_url: !env_var SONARR_BASE_URL
    api_key: !env_var SONARR_API_KEY

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    quality_definition:
      type: series

    quality_profiles:
      # WEB-1080p
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        name: WEB-1080p
        reset_unmatched_scores:
          enabled: true

      # WEB-2160p
      - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
        name: WEB-2160p
        reset_unmatched_scores:
          enabled: true
