# yaml-language-server: $schema=https://raw.githubusercontent.com/recyclarr/recyclarr/master/schemas/config-schema.json

sonarr:
  sonarr:
    base_url: !env_var SONARR_BASE_URL
    api_key: !env_var SONARR_API_KEY

    media_naming:
      series: default
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default

    include:
      # Quality Definition
      - template: sonarr-quality-definition-series

      # WEB-1080p
      - template: sonarr-v4-quality-profile-web-1080p
      - template: sonarr-v4-custom-formats-web-1080p

      # WEB-2160p
      - template: sonarr-v4-quality-profile-web-2160p
      - template: sonarr-v4-custom-formats-web-2160p
