services:
  app:
    image: linuxserver/smokeping:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - data:/data
      - config:/config
    ports:
      - 8070:80

volumes:
  data:
  config:
