services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /docker/appdata/jellystat/db:/var/lib/postgresql/data

  jellystat:
    image: cyfershepard/jellystat:latest
    restart: unless-stopped
    container_name: jellystat
    environment:
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8097:3000
    volumes:
      - /docker/appdata/jellystat/data:/app/backend/backup-data
    depends_on:
      - db
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.jellystat.rule=Host(`jellystat.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
