services:
  db:
    image: postgres:15.2
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - /docker/appdata/jellystat/db:/var/lib/postgresql/data

  app:
    image: cyfershepard/jellystat:latest
    restart: unless-stopped
    container_name: jellystat
    environment:
      - POSTGRES_IP=${POSTGRES_IP}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 8097:3000
    volumes:
      - /docker/appdata/jellystat/data:/app/backend/backup-data
    depends_on:
      - db

