services:
  postgres:
    container_name: postgres
    image: postgres:18
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - TZ=Asia/Jakarta
      - PGDATA=/data/postgres
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    volumes:
      - postgres:/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

  pg-backup:
    image: prodrigestivill/postgres-backup-local:18
    container_name: pg-backup
    restart: unless-stopped
    secrets:
      - postgres_user
      - postgres_password
    environment:
      - TZ=Asia/Jakarta
      - POSTGRES_HOST=postgres
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_DB=postgres
      - POSTGRES_CLUSTER=true
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
    volumes:
      - /backup/database/postgres:/backups
    depends_on:
      postgres:
        condition: service_healthy

secrets:
  postgres_user:
    file: './secrets/postgres_user'
  postgres_password:
    file: './secrets/postgres_password'

volumes:
  postgres:
