services:
  postgres:
    container_name: postgres
    image: postgres:16
    secrets:
      - postgres_user
      - postgres_password
    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    secrets:
      - pgadmin_default_password
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD_FILE: /run/secrets/pgadmin_default_password
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

secrets:
  postgres_user:
    file: './secrets/postgres_user'
  postgres_password:
    file: './secrets/postgres_password'
  pgadmin_default_password:
    file: './secrets/pgadmin_default_password'

volumes:
    postgres:
    pgadmin:

