services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/portainer:/data
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.portainer.rule=Host(`portainer.${SECONDARY_MAIN_DOMAIN}`)'
      - 'traefik.http.services.portainer.loadbalancer.server.port=9000'

networks:
  default:
    name: traefik
    external: true
