services:
  app:
    image: portainer/portainer-ee:latest
    container_name: portainer 
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9443:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker/appdata/portainer:/data

