http:
  routers:
    jellyfin:
      rule: Host(`jellyfin.{{ env "DOMAIN_MAIN_PRIMARY" }}`)
      service: jellyfin
      middlewares:
        - allow-trusted-geo-ips
        - jellyfin-rate-limit

    navidrome:
      rule: Host(`navidrome.{{ env "DOMAIN_MAIN_PRIMARY" }}`)
      service: navidrome
      middlewares:
        - allow-trusted-geo-ips
        - jellyfin-rate-limit

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: http://wg-easy:8096

    navidrome:
      loadBalancer:
        servers:
          - url: http://wg-easy:4533
