http:
  routers:
    v2fly-vmess-proxy:
      rule: Host(`3706161e-d7a3-4786-9eef-7d087f5443ca.ccrsxx.my.id`) && Path(`/vmess`)
      service: v2fly-vmess-proxy
      middlewares:
        - cloudflare-ip-allowlist@file
        - public-rate-limit@file

    v2fly-trojan-proxy:
      rule: Host(`3706161e-d7a3-4786-9eef-7d087f5443ca.ccrsxx.my.id`) && Path(`/trojan`)
      service: v2fly-trojan-proxy
      middlewares:
        - cloudflare-ip-allowlist@file
        - public-rate-limit@file

  services:
    v2fly-vmess-proxy:
      loadBalancer:
        servers:
          - url: http://{{ env "PROXY_VPS_IP" }}:10086

    v2fly-trojan-proxy:
      loadBalancer:
        servers:
          - url: http://{{ env "PROXY_VPS_IP" }}:10087
