http:
  routers:
    adguard-home:
      rule: (Host(`dns.{{ env "PRIMARY_MAIN_DOMAIN" }}`) || Host(`dns.{{ env "SECONDARY_MAIN_DOMAIN" }}`)) && Path(`/dns-query`)
      service: adguard-home
      middlewares:
        - cloudflare-ip-allowlist@file

  services:
    adguard-home:
      loadBalancer:
        servers:
          - url: http://{{ env "DNS_VPS_IP" }}:80
