http:
  routers:
    v2fly-vmess-proxy:
      rule: Host(`{{ env "WS_PROXY_ROUTER" }}.{{ env "SECONDARY_MAIN_DOMAIN" }}`) && Path(`/vmess`)
      service: v2fly-vmess-proxy
      middlewares:
        - cloudflare-ip-allowlist@file
        - public-rate-limit@file

    v2fly-trojan-proxy:
      rule: Host(`{{ env "WS_PROXY_ROUTER" }}.{{ env "SECONDARY_MAIN_DOMAIN" }}`) && Path(`/trojan`)
      service: v2fly-trojan-proxy
      middlewares:
        - cloudflare-ip-allowlist@file
        - public-rate-limit@file

  services:
    v2fly-vmess-proxy:
      loadBalancer:
        servers:
          - url: http://{{ env "PROXY_VPS_IP" }}:10086

    v2fly-trojan-proxy:
      loadBalancer:
        servers:
          - url: http://{{ env "PROXY_VPS_IP" }}:10087
