targets:
  # --- Public DNS Resolvers ---
  - host: 1.1.1.1
    type: dns
    name: 'Cloudflare Primary'
  - host: 1.0.0.1
    type: dns
    name: 'Cloudflare Secondary'
  - host: 8.8.8.8
    type: dns
    name: 'Google Primary'
  - host: 8.8.4.4
    type: dns
    name: 'Google Secondary'
  - host: 9.9.9.9
    type: dns
    name: 'Quad9'
  - host: 208.67.222.222
    type: dns
    name: 'OpenDNS'

  # --- Public Websites ---
  - host: x.com
    type: web
    name: 'X (Twitter)'
  - host: reddit.com
    type: web
    name: 'Reddit'
  - host: tiktok.com
    type: web
    name: 'TikTok'
  - host: google.com
    type: web
    name: 'Google'
  - host: discord.com
    type: web
    name: 'Discord'
  - host: youtube.com
    type: web
    name: 'YouTube'
  - host: facebook.com
    type: web
    name: 'Facebook'
  - host: instagram.com
    type: web
    name: 'Instagram'

dns:
  refresh: 2m
  nameserver: 1.1.1.1

ping:
  interval: 2s
  timeout: 1s
  history-size: 30

options:
  disable-ipv6: true
