services:
  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    restart: unless-stopped
    command: run -c /etc/v2fly/config.json
    volumes:
      - '.${CUSTOM_CONFIG_DIR}/config.json:/etc/v2fly/config.json'
    ports:
      - 10086:10086
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.v2fly-vmess.rule=Host(`${VMESS_ROUTER}.${SECONDARY_MAIN_DOMAIN}`) && Path(`/vmess`)'
      - 'traefik.http.routers.v2fly-vmess.middlewares=rate-limit@file'
      - 'traefik.http.services.v2fly-vmess.loadbalancer.server.port=10086'

networks:
  default:
    name: traefik
    external: true
