services:
  v2fly:
    image: v2fly/v2fly-core:latest
    container_name: v2fly
    restart: unless-stopped
    command: run -c /etc/v2fly/config.json
    volumes:
      - '.${CUSTOM_CONFIG_DIR}/config.json:/etc/v2fly/config.json'
    ports:
      - 10086:10086
      - 10087:10087
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'

      # VMess labels
      - 'traefik.http.routers.v2fly-vmess.service=v2fly-vmess'
      - 'traefik.http.routers.v2fly-vmess.rule=Host(`${WS_ROUTER}.${SECONDARY_MAIN_DOMAIN}`) && Path(`/vmess`)'
      - 'traefik.http.routers.v2fly-vmess.middlewares=cloudflare-ip-allowlist@file,public-rate-limit@file'
      - 'traefik.http.services.v2fly-vmess.loadbalancer.server.port=10086'

      # Trojan labels
      - 'traefik.http.routers.v2fly-trojan.service=v2fly-trojan'
      - 'traefik.http.routers.v2fly-trojan.rule=Host(`${WS_ROUTER}.${SECONDARY_MAIN_DOMAIN}`) && Path(`/trojan`)'
      - 'traefik.http.routers.v2fly-trojan.middlewares=cloudflare-ip-allowlist@file,public-rate-limit@file'
      - 'traefik.http.services.v2fly-trojan.loadbalancer.server.port=10087'

networks:
  default:
    name: traefik
    external: true
