apiVersion: 1

datasources:
  - uid: prometheus-vps
    name: Prometheus VPS
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: 5s

  - uid: prometheus-homelab
    name: Prometheus Homelab
    type: prometheus
    access: proxy
    url: http://wg-easy:9091
    isDefault: false
    jsonData:
      timeInterval: 5s
