services:
  ntopng:
    image: ntop/ntopng:stable
    container_name: ntopng
    restart: unless-stopped
    command:
      [
        '-i',
        'tcp://nprobe:5557',
        '-i',
        'tcp://netflow2ng:5556',
        '-m',
        '/etc/ntopng/localnetworks.txt',
        '--community'
      ]
    entrypoint: /entrypoint.sh
    ports:
      - 3030:3000
    depends_on:
      - nprobe
      - netflow2ng
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - /docker/appdata/ntopng/data:/var/lib/ntopng
      - /docker/appdata/ntopng/redis:/var/lib/redis
      - ./entrypoint.sh:/entrypoint.sh
      - ./localnetworks.txt:/etc/ntopng/localnetworks.txt:ro
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-true}'
      - 'traefik.http.routers.ntopng.rule=Host(`ntopng.${SECONDARY_MAIN_DOMAIN}`)'

  nprobe:
    container_name: nprobe
    restart: unless-stopped
    image: ntop/nprobe:stable
    command: ['--zmq', 'tcp://*:5557', '--collector-port', '2056']
    ports:
      - 5557:5557/tcp
      - 2056:2056/udp

  netflow2ng:
    container_name: netflow2ng
    restart: unless-stopped
    image: synfinatic/netflow2ng:latest
    ports:
      - 5556:5556/tcp
      - 2055:2055/udp

  restarter:
    image: docker:cli
    container_name: restarter
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./restarter.sh:/restarter.sh
    entrypoint: /restarter.sh

networks:
  default:
    name: traefik
    external: true
