services:
  ntopng:
    image: ntop/ntopng:stable
    container_name: ntopng
    restart: unless-stopped
    command: ["ntopng", "-i", "tcp://netflow2ng:5556"]
    ports:
      - "3000:3000"
    depends_on:
      - netflow2ng

  netflow2ng:
    container_name: netflow2ng
    restart: unless-stopped
    image: synfinatic/netflow2ng:latest
    entrypoint: /netflow2ng
    ports:
      - 5556:5556/tcp
      - 2055:2055/udp

