services:
  grafana:
    image: grafana/grafana:13.2.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3333:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
    environment:
      - GRAFANA_ROOT_URL=${GRAFANA_ROOT_URL}
      - GRAFANA_ADMIN_EMAIL=${GRAFANA_ADMIN_EMAIL}
      - POCKET_ID_CLIENT_ID=${POCKET_ID_CLIENT_ID}
      - POCKET_ID_AUTH_URL=${POCKET_ID_AUTH_URL}
      - POCKET_ID_TOKEN_URL=${POCKET_ID_TOKEN_URL}
      - POCKET_ID_API_URL=${POCKET_ID_API_URL}
    secrets:
      - grafana_password
      - pocket_id_secret
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v3.14.0
    container_name: prometheus
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--storage.tsdb.retention.size=1GB'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    networks:
      - default
      - monitoring

  ping-exporter:
    image: czerwonk/ping_exporter:1.2.3
    container_name: ping-exporter
    restart: unless-stopped
    environment:
      - CONFIG_FILE=/etc/ping-exporter/ping-exporter.yaml
    volumes:
      - ./ping-exporter/ping-exporter.yaml:/etc/ping-exporter/ping-exporter.yaml:ro
    ports:
      - '9427:9427'

secrets:
  grafana_password:
    file: './secrets/grafana_password'
  pocket_id_secret:
    file: ./secrets/pocket_id_secret

networks:
  monitoring:
    external: true

volumes:
  grafana-data:
  prometheus-data:
