services:
  app:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader2
    restart: unless-stopped
    ports:
      - '5800:5800'
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - '${CONFIG_PATH:-/mnt/docker/jdownloader2/config}:/config:rw'
      - '${DOWNLOADS_PATH:-/mnt/docker/jdownloader2/downloads}:/output:rw'
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.jdownloader.rule=Host(`jdownloader.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
