services:
  app:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader2
    restart: unless-stopped
    ports:
      - '5800:5800'
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - '/mnt/docker/jdownloader2/config:/config:rw'
      - '/mnt/docker/jdownloader2/downloads:/output:rw'

