services:
  jdownloader2:
    image: jlesage/jdownloader-2:latest
    container_name: jdownloader2
    restart: unless-stopped
    ports:
      - '5800:5800'
    environment:
      - TZ=Asia/Jakarta
    volumes:
      - '/docker/appdata/jdownloader2/config:/config:rw'
      - '${DOWNLOADS_PATH:-/mnt/docker/jdownloader2/downloads}:/output:rw'
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.jdownloader.rule=Host(`jdownloader.${DOMAIN_MAIN_SECONDARY}`)'
      - 'traefik.http.services.jdownloader.loadbalancer.server.port=5800'

networks:
  default:
    name: traefik
    external: true
