services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Jakarta
    ports:
      - 5055:5055
    volumes:
      - /docker/appdata/jellyseerr:/app/config
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
