services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /docker/appdata/beszel-agent:/var/lib/beszel-agent
    environment:
      - KEY=${KEY}
      - TOKEN=${TOKEN}
      - HUB_URL=${HUB_URL}
      - DISABLE_SSH=true
