services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:5.27.5
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=10000
      - PGID=10000
      - UMASK=002
      - TZ=Asia/jakarta
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/data:/data
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.${DOMAIN_MAIN_SECONDARY}`)'
      - 'traefik.http.routers.radarr.middlewares=radarr-theme@file'

networks:
  default:
    name: traefik
    external: true
