services:
  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    restart: unless-stopped
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/jakarta
    volumes:
      - /docker/appdata/radarr:/config
      - /mnt/data:/data
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-true}'
      - 'traefik.http.routers.radarr.rule=Host(`radarr.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
