http:
  routers:
    iconnet-router:
      rule: Host(`iconnet.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: iconnet-router

    mikrotik-router:
      rule: Host(`mikrotik.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: mikrotik-router

    primary-switch:
      rule: Host(`switch-primary.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: primary-switch

    secondary-switch:
      rule: Host(`switch-secondary.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: secondary-switch

    adguard-home:
      rule: Host(`adguard.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: adguard-home
      middlewares:
        - adguard-home-theme@file

    uptime-kuma:
      rule: Host(`status.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: uptime-kuma

  services:
    iconnet-router:
      loadBalancer:
        servers:
          - url: http://10.0.1.1:80

    mikrotik-router:
      loadBalancer:
        servers:
          - url: http://192.168.1.1:80

    primary-switch:
      loadBalancer:
        servers:
          - url: http://192.168.20.30:80

    secondary-switch:
      loadBalancer:
        servers:
          - url: http://192.168.20.40:80

    adguard-home:
      loadBalancer:
        servers:
          - url: http://10.0.10.10:80

    uptime-kuma:
      loadBalancer:
        servers:
          - url: http://10.0.10.20:3001
