# Global settings
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# Log settings
log:
  level: DEBUG

# API and dashboard
api:
  dashboard: true

# Servers transport (for skipping self-signed certificates)
serversTransport:
  insecureSkipVerify: true

# Entry points configuration
entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: 'websecure'
          scheme: 'https'
  websecure:
    address: ':443'
    asDefault: true
    http:
      tls:
        certResolver: letsencrypt
        domains:
          - main: '{{ env "PRIMARY_MAIN_DOMAIN" }}}'
            sans: '{{ env "PRIMARY_WILDCARD_DOMAIN" }}'
          - main: '{{ env "SECONDARY_MAIN_DOMAIN" }}'
            sans: '{{ env "SECONDARY_WILDCARD_DOMAIN" }}'

# Certificates resolvers configuration
certificatesResolvers:
  letsencrypt:
    acme:
      email: '{{ env "CLOUDFLARE_EMAIL" }}'
      storage: '/letsencrypt/acme.json'
      dnsChallenge:
        provider: 'cloudflare'
        resolvers:
          - '1.1.1.1:53'
          - '8.8.8.8:53'
        delayBeforeCheck: 60

# Providers configuration
providers:
  docker:
    watch: true
    exposedByDefault: false
  file:
    watch: true
    directory: '/config/dynamic'
