http:
  routers:
    wg-easy:
      rule: Host(`wireguard.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: wg-easy

    traefik-vps:
      rule: Host(`traefik-vps.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: traefik-vps
      middlewares:
        - basic-auth@file

    smokeping-vps:
      rule: Host(`smokeping-vps.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: smokeping-vps

    adguard-home-sync:
      rule: Host(`adguard-vps-sync.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: adguard-home-sync

    adguard-home-vps-main:
      rule: Host(`adguard-vps-main.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: adguard-home-vps-main

    adguard-home-vps-dns:
      rule: Host(`adguard-vps-dns.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: adguard-home-vps-dns

    openspeedtest-vps:
      rule: Host(`openspeedtest-vps.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: openspeedtest-vps

  services:
    wg-easy:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:51821

    traefik-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8010

    smokeping-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8070

    adguard-home-sync:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8022

    adguard-home-vps-main:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8888

    adguard-home-vps-dns:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_DNS" }}:8888

    openspeedtest-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8081
