http:
  routers:
    wg-easy:
      rule: Host(`wireguard.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: wg-easy

    traefik-vps:
      rule: Host(`traefik-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: traefik-vps
      middlewares:
        - basic-auth@file

    smokeping-vps:
      rule: Host(`smokeping-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: smokeping-vps

    adguard-home-vps-main:
      rule: Host(`adguard-vps-main.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: adguard-home-vps-main

    adguard-home-vps-dns:
      rule: Host(`adguard-vps-dns.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: adguard-home-vps-dns

    openspeedtest-vps:
      rule: Host(`openspeedtest-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: openspeedtest-vps

  services:
    wg-easy:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:51821

    traefik-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8010

    smokeping-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8070

    adguard-home-vps-main:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8888

    adguard-home-vps-dns:
      loadBalancer:
        servers:
          - url: http://{{ env "DNS_VPS_IP" }}:8888

    openspeedtest-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8081
