http:
  routers:
    beszel-vps:
      rule: Host(`beszel.{{ env "DOMAIN_MAIN_SECONDARY" }}`)
      service: beszel-vps

  services:
    beszel-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "IP_VPS_MAIN" }}:8088
