http:
  routers:
    wg-easy:
      rule: Host(`wireguard.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: wg-easy

    cockpit-main:
      rule: Host(`cockpit-main.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: cockpit-main

    cockpit-dns:
      rule: Host(`cockpit-dns.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: cockpit-dns

    cockpit-proxy:
      rule: Host(`cockpit-proxy.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: cockpit-proxy

    pgadmin-vps:
      rule: Host(`pgadmin-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: pgadmin-vps

    portainer-vps:
      rule: Host(`portainer-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: portainer-vps

    smokeping-vps:
      rule: Host(`smokeping-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: smokeping-vps

    adguard-home-vps:
      rule: Host(`adguard-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: adguard-home-vps

    jdownloader-vps:
      rule: Host(`download-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: jdownloader-vps

    openspeedtest-vps:
      rule: Host(`openspeedtest-vps.{{ env "SECONDARY_MAIN_DOMAIN" }}`)
      service: openspeedtest-vps

  services:
    wg-easy:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:51821

    cockpit-main:
      loadBalancer:
        servers:
          - url: https://{{ env "MAIN_VPS_IP" }}:9090

    cockpit-dns:
      loadBalancer:
        servers:
          - url: https://{{ env "DNS_VPS_IP" }}:9090

    cockpit-proxy:
      loadBalancer:
        servers:
          - url: https://{{ env "PROXY_VPS_IP" }}:9090

    pgadmin-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:5050

    portainer-vps:
      loadBalancer:
        servers:
          - url: https://{{ env "MAIN_VPS_IP" }}:9443

    smokeping-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8080

    adguard-home-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "DNS_VPS_IP" }}:80

    jdownloader-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:5800

    openspeedtest-vps:
      loadBalancer:
        servers:
          - url: http://{{ env "MAIN_VPS_IP" }}:8081
