services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    ports:
      - 8024:8080
    volumes:
      - './data:/home/coder'
    environment:
      DOCKER_USER: '${USER}'
    user: '${UID:-1000}:${GID:-1000}'
    cpus: '2'
    mem_limit: '4gb'
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.code-server.rule=Host(`code.${DOMAIN_MAIN_PRIMARY}`) || Host(`code.${DOMAIN_MAIN_SECONDARY}`)'
      - 'traefik.http.routers.code-server.middlewares=cloudflare-ip-allowlist@file,public-ip-allowlist@file'

networks:
  default:
    name: traefik
    external: true
