services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    restart: unless-stopped
    volumes:
      - './data:/home/coder'
    environment:
      DOCKER_USER: '${USER}'
    user: '${UID:-1000}:${GID:-1000}'
    cpus: '2'
    mem_limit: '4gb'
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED}'
      - 'traefik.http.routers.code-server.rule=Host(`code.${PRIMARY_MAIN_DOMAIN}`) || Host(`code.${SECONDARY_MAIN_DOMAIN}`)'
      - 'traefik.http.routers.code-server.middlewares=cloudflare-ip-allowlist@file,public-ip-allowlist@file'

networks:
  default:
    name: traefik
    external: true
