services:
  komga:
    image: gotson/komga:latest
    container_name: komga
    volumes:
      - /docker/appdata/komga:/config
      - /mnt/data/media:/data/media
    ports:
      - 25600:25600
    environment:
      - TZ=Asia/Jakarta
    restart: unless-stopped
    cpus: 1
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-true}'
      - 'traefik.http.routers.komga.rule=Host(`komga.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
