services:
  smokeping:
    image: linuxserver/smokeping:latest
    container_name: smokeping
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
    ports:
      - 8070:80
    restart: unless-stopped
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-true}'
      - 'traefik.http.routers.smokeping.rule=Host(`smokeping.${SECONDARY_MAIN_DOMAIN}`)'

networks:
  default:
    name: traefik
    external: true
