services:
  app:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
