services:
  tailscale:
    image: tailscale/tailscale:latest
    restart: unless-stopped
    hostname: homelab
    container_name: tailscale
    environment:
      - TS_AUTHKEY=${TS_OAUTH_KEY}?ephemeral=false
      - TS_ROUTES=${TS_ROUTES}
      - TS_EXTRA_ARGS=--advertise-exit-node --advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
    volumes:
      - tailscale-data:/var/lib/tailscale

volumes:
  tailscale-data:
