services:
  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi
    environment:
      - PUID=10000
      - PGID=10000
      - UMASK=002
      - TZ=Asia/Jakarta
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - /docker/appdata/unifi/config:/config
    ports:
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 1900:1900/udp
      - 3478:3478/udp
      - 5514:5514/udp
      - 10001:10001/udp
    restart: unless-stopped
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.unifi.rule=Host(`unifi.${DOMAIN_MAIN_SECONDARY}`)'
      - 'traefik.http.services.unifi.loadbalancer.server.port=8443'
      - 'traefik.http.services.unifi.loadbalancer.server.scheme=https'

  unifi-db:
    image: mongo:8
    container_name: unifi-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DBNAME=unifi
      - MONGO_AUTHSOURCE=admin
    volumes:
      - /docker/appdata/unifi/db:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    restart: unless-stopped

networks:
  default:
    name: traefik
    external: true
