services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5
    container_name: tinyauth
    restart: unless-stopped
    environment:
      - TINYAUTH_LOG_LEVEL=info
      - TINYAUTH_APPURL=${APP_URL}
      - TINYAUTH_UI_TITLE=Auth
      - TINYAUTH_UI_BACKGROUNDIMAGE=${BACKGROUND_IMAGE}
      - TINYAUTH_ANALYTICS_ENABLED=false
      - TINYAUTH_AUTH_SESSIONEXPIRY=604800 # 1 week

      - TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID=${GOOGLE_CLIENT_ID}
      - TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET=${GOOGLE_CLIENT_SECRET}
      - TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID=${GITHUB_CLIENT_ID}
      - TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET=${GITHUB_CLIENT_SECRET}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTID=${PROVIDERS_POCKETID_CLIENT_ID}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_CLIENTSECRET=${PROVIDERS_POCKETID_CLIENT_SECRET}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_AUTHURL=${PROVIDERS_POCKETID_AUTH_URL}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_TOKENURL=${PROVIDERS_POCKETID_TOKEN_URL}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_USERINFOURL=${PROVIDERS_POCKETID_USER_INFO_URL}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_REDIRECTURL=${PROVIDERS_POCKETID_REDIRECT_URL}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_SCOPES=${PROVIDERS_POCKETID_SCOPES}
      - TINYAUTH_OAUTH_PROVIDERS_POCKETID_NAME=${PROVIDERS_POCKETID_NAME}

      - TINYAUTH_AUTH_USERS=${USERS}

      - TINYAUTH_APPS_METUBE_CONFIG_DOMAIN=metube.${DOMAIN_MAIN_PRIMARY}
      - TINYAUTH_APPS_METUBE_PATH_ALLOW=^\/(download|audio_download)

      - TINYAUTH_APPS_FRIGATE_CONFIG_DOMAIN=frigate.${DOMAIN_MAIN_PRIMARY}
      - TINYAUTH_APPS_FRIGATE_USERS_ALLOW=${FRIGATE_USER_WHITELIST}
      - TINYAUTH_APPS_FRIGATE_OAUTH_WHITELIST=${FRIGATE_OAUTH_WHITELIST}

      - TINYAUTH_APPS_JELLYFIN_CONFIG_DOMAIN=jellyfin.${DOMAIN_MAIN_PRIMARY}
      - TINYAUTH_APPS_JELLYFIN_IP_BYPASS=${JELLYFIN_IP_WHITELIST}
      - TINYAUTH_APPS_JELLYFIN_PATH_ALLOW=${JELLYFIN_PATH_WHITELIST}

      - TINYAUTH_APPS_CHANGEDETECTION_CONFIG_DOMAIN=change.${DOMAIN_MAIN_PRIMARY}
      - TINYAUTH_APPS_CHANGEDETECTION_USERS_ALLOW=${PRIVATE_USER_WHITELIST}
      - TINYAUTH_APPS_CHANGEDETECTION_OAUTH_WHITELIST=${PRIVATE_OAUTH_WHITELIST}
    labels:
      - 'traefik.enable=${TRAEFIK_ENABLED:-false}'
      - 'traefik.http.routers.tinyauth.rule=Host(`auth.${DOMAIN_MAIN_PRIMARY}`)'
      - 'traefik.http.middlewares.tinyauth.forwardauth.address=http://tinyauth:3000/api/auth/traefik'
    networks:
      - traefik

networks:
  traefik:
    external: true
